sudo: false

matrix:
  include:
    # Frontend build test
    - language: node_js
      nodejs:
        - 12
    
    # Python with sqlite
    - language: python
      env:
        - DATABASE=sqlite
      python:
         - "3.7"
    
    # Python with Postgres
    - language: python
      env:
        - DATABASE=postgres
      services:
        - postgresql
      python:
        - "3.7"
    
    # Docker build test
    - language: minimal
      services:
        - docker

before_install:
  - if [ ! -z "$TRAVIS_NODE_VERSION" ]; then cd frontend; fi

install:
  - if [ ! -z "$TRAVIS_NODE_VERSION" ]; then yarn install; fi
  - if [ ! -z "$TRAVIS_PYTHON_VERSION" ]; then pip install -r requirements.txt; fi
  - if [ ! -z "$TRAVIS_PYTHON_VERSION" ]; then pip install -r requirements-dev.txt; fi

script:
  - if [ ! -z "$TRAVIS_NODE_VERSION" ]; then yarn build; fi
  - if [ ! -z "$TRAVIS_PYTHON_VERSION" ]; then pytest -v; fi
  - if [ -z "$TRAVIS_NODE_VERSION" ] && [ -z "$TRAVIS_PYTHON_VERSION" ]; then docker build -t mathhub/mdh .; fi

