matrix:
  include:
    - name: "Frontend: NodeJS 12"
      language: node_js
      nodejs:
        - 12
    
    - name: "Backend: CPython 3.7 / sqlite"
      language: python
      env:
        - DATABASE=sqlite
      python:
         - "3.7"
    
    - name: "Backend: CPython 3.7 / PostgreSQL"
      language: python
      env:
        - DATABASE=postgres
      services:
        - postgresql
      python:
        - "3.7"
    
    - name: "Backend: PyPy 3.6 / sqlite" 
      language: python
      env:
        - DATABASE=sqlite
        - PYPY=pypy3.6-v7.1.1-linux64
      python: 3.6
 
    - name: "Backend: PyPy 3.6 / PostgreSQL"
      language: python
      env:
        - DATABASE=postgres
        - PYPY=pypy3.6-v7.1.1-linux64
      services:
        - postgresql
      python: 3.6
    
    - name: "Docker Build"
      language: minimal
      services:
        - docker

before_install:
  - if [ ! -z "$PYPY" ]; then pushd $HOME; wget -c https://bitbucket.org/pypy/pypy/downloads/$PYPY.tar.bz2  -O - | tar xj; $PYPY/bin/pypy3 -m venv pypyenv; source pypyenv/bin/activate; popd; fi
  - if [ ! -z "$TRAVIS_NODE_VERSION" ]; then cd frontend; fi

install:
  - if [ ! -z "$TRAVIS_NODE_VERSION" ]; then yarn install; fi
  - if [ ! -z "$TRAVIS_PYTHON_VERSION" ]; then pip install -r requirements.txt; fi
  - if [ ! -z "$TRAVIS_PYTHON_VERSION" ]; then pip install -r requirements-dev.txt; fi

script:
  - if [ ! -z "$TRAVIS_NODE_VERSION" ]; then yarn build; fi
  - if [ ! -z "$TRAVIS_NODE_VERSION" ]; then yarn test; fi
  - if [ ! -z "$TRAVIS_PYTHON_VERSION" ]; then pytest -v; fi
  - if [ -z "$TRAVIS_NODE_VERSION" ] && [ -z "$TRAVIS_PYTHON_VERSION" ]; then docker build -t mathhub/mhd .; fi

